name: Check

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@master

    - name: Setup Environment
      run: brew install clang-format typos-cli

    - name: Check Code Format
      run: |
        make format
        git diff --exit-code

    - name: Find Typos
      run: typos . .github
