name: Check

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/check.yml'
      - 'Makefile'
      - 'bin/**'
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@master

    - name: Setup Environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends clang-format

    - name: Check Code Format
      run: |
        make format
        git diff --exit-code
