name: Check

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**/*.c'
      - '**/*.h'
      - '.github/workflows/check.yml'
      - 'Makefile'
  pull_request:
    branches: [main]
    paths:
      - '**/*.c'
      - '**/*.h'
      - '.github/workflows/check.yml'
      - 'Makefile'

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@master

    - name: Setup Environment
      run: brew install clang-format

    - name: Check Code Format
      run: |
        make format
        git diff --exit-code
