name: macOS

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/macos.yml'
      - 'Makefile'
      - 'assets/**'
      - 'bin/**'
      - 'src/**'
      - 'tests/**'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write       # for actions/upload-release-asset to upload release asset
    runs-on: macos-latest

    env:
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_macos

    steps:
    - name: Checkout this repo
      uses: actions/checkout@master

    - name: Setup Release Paths
      run: echo "PROJECT_RELEASE_PATH=${{ env.PROJECT_NAME }}_v${{ github.event.release.tag_name }}_macos" >> "$GITHUB_ENV"
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Setup Environment
      run: brew install raylib just

    - name: Build Product
      run: make -B -j3

    - name: Run tests
      run: just test

    - name: Generate Artifacts
      run: |
        mkdir -p ${{ env.PROJECT_RELEASE_PATH }}
        make PREFIX=${{ env.PROJECT_RELEASE_PATH }} install
        7z a ./${{ env.PROJECT_RELEASE_PATH }}.zip ./${{ env.PROJECT_RELEASE_PATH }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_RELEASE_PATH }}.zip
        path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.PROJECT_RELEASE_PATH }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'
