name: WebAssembly

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.html'
      - '.github/workflows/webassembly.yml'
      - 'Makefile'
      - 'assets/**'
  pull_request:
    branches: [main]
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.html'
      - '.github/workflows/webassembly.yml'
      - 'Makefile'
      - 'assets/**'
  release:
    types: [published]

permissions:
  contents: read

env:
  PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_wasm
  RAYLIB_VERSION: 5.5
  RAYLIB_SRC_PATH: raylib/src
  PLATFORM: PLATFORM_WEB
  EM_VERSION: 4.0.13
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    permissions:
      contents: write # for actions/upload-release-asset & GitHub Pages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@master

    - name: Checkout raylib repo
      uses: actions/checkout@v4
      with:
        repository: raysan5/raylib
        path: raylib

    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v4
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}

    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{env.EM_VERSION}}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

    - name: Setup Release Paths
      run: |
        echo "PROJECT_RELEASE_PATH=${{ env.PROJECT_NAME }}_v${{ github.event.release.tag_name }}_wasm" >> "$GITHUB_ENV"
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Build raylib Library
      run: |
        cd raylib/src
        emcc -v
        make PLATFORM=PLATFORM_WEB RAYLIB_BUILD_MODE=RELEASE RAYLIB_LIBTYPE=STATIC RAYLIB_RELEASE_PATH=. -B -j "$(nproc)"

    - name: Build Product
      run: make -B -j "$(nproc)" games

    - name: Generate Artifacts
      run: |
        mkdir -p ${{ env.PROJECT_RELEASE_PATH }}
        cp src/index.html ${{ env.PROJECT_RELEASE_PATH }}
        cp game/*.html game/*.js game/*.wasm game/*.data ${{ env.PROJECT_RELEASE_PATH }}
        7z a ./${{ env.PROJECT_RELEASE_PATH }}.zip ./${{ env.PROJECT_RELEASE_PATH }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_RELEASE_PATH }}.zip
        path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.PROJECT_RELEASE_PATH }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      contents: write # for GitHub Pages
      pages: write # for GitHub Pages
      id-token: write # for GitHub Pages

    concurrency:
      group: "pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.PROJECT_RELEASE_PATH }}.zip
      - name: Decompress Artifacts
        run: unzip ${{ env.PROJECT_RELEASE_PATH }}.zip
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./${{ env.PROJECT_RELEASE_PATH }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
