name: Windows

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/windows.yml'
      - 'Makefile'
      - 'assets/**'
      - 'bin/**'
      - 'src/**'
      - 'tests/**'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write       # for actions/upload-release-asset to upload release asset
    runs-on: windows-latest

    env:
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_win_x64
      RAYLIB_VERSION: 5.5
      RAYLIB_PATH: raylib-5.5_win64_mingw-w64
      CC: x86_64-w64-mingw32-gcc

    steps:
    - name: Checkout this repo
      uses: actions/checkout@master

    - name: Setup Release Paths
      run: |
        echo "PROJECT_RELEASE_PATH=${{ env.PROJECT_NAME }}_v${{ github.event.release.tag_name }}_win_x64" >> "$GITHUB_ENV"
      shell: bash
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Setup Environment
      run: |
        choco install -q just curl
        curl -OL "https://github.com/raysan5/raylib/releases/download/$RAYLIB_VERSION/$RAYLIB_PATH.zip"
        unzip "$RAYLIB_PATH.zip"
        echo RAYLIB_CFLAGS="-I$RAYLIB_PATH/include" >> "$GITHUB_ENV"
        echo RAYLIB_LDFLAGS="-L$RAYLIB_PATH/lib -lraylib -lgdi32 -lwinmm" >> "$GITHUB_ENV"
      shell: bash

    - name: Build Product
      run: |
        x86_64-w64-mingw32-gcc --version
        make -B -j4
      shell: bash

    - name: Run tests
      run: |
        ls tests
        just test
      shell: bash

    - name: Generate Artifacts
      run: |
        mkdir ${{ env.PROJECT_RELEASE_PATH }}
        make PREFIX=${{ env.PROJECT_RELEASE_PATH }} install
        7z a .\${{ env.PROJECT_RELEASE_PATH }}.zip .\${{ env.PROJECT_RELEASE_PATH }}
      shell: cmd

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_RELEASE_PATH }}.zip
        path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.PROJECT_RELEASE_PATH }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'
